language: java
jdk: oraclejdk8
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -B
before_install:
- openssl aes-256-cbc -K $encrypted_b66d7a90883a_key -iv $encrypted_b66d7a90883a_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
addons:
  ssh_known_hosts: 172.16.75.27
after_success:
- ssh JustMeliyu@172.16.75.27 "./travis_build"
